production:
  sessions:
    default:
      database: medcodeassist
      hosts:
        - localhost:27017
development:
  sessions:
    default:
      database: medcodeassist
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: medcodeassist
      hosts:
          - localhost:27017


