development:
  clients:
    default:
      database: medcodeassist
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: medcodeassist
      hosts:
        - localhost:27017
